name: Run tests

on:
  push:  # Runs on push to any branch

jobs:
  test-utils:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4  # clones your repository to the virtual server

    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: SWE4S_hw

    - name: Run test/test_utils.py
      run: python test/test_utils.py

  test-print-fires-functional:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4  # clones the repository to the virtual server

    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: SWE4S_hw

    - name: run test/test_print_fires.sh
      run: bash test/test_print_fires.sh

  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: SWE4S_hw

    - name: Run pycodestyle style checks
      shell: bash
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate SWE4S_hw
        shopt -s globstar
        pycodestyle "**/*.py"
